from typing import Any

SDK_VERSION: str
SDK_REVISION: str

class OmniBCIError(Exception): ...
class DeviceTimeoutError(OmniBCIError): ...
class InvalidStateError(OmniBCIError): ...
class ConfigurationError(OmniBCIError): ...
class DisconnectedError(OmniBCIError): ...
class BufferOverflowError(OmniBCIError): ...
class TransportError(OmniBCIError): ...

class NativeDevice:
    @staticmethod
    def connect(endpoint: str, timeout: float) -> NativeDevice: ...
    def start(self, timeout: float) -> None: ...
    def stop(self, timeout: float) -> None: ...
    def close(self, timeout: float) -> None: ...
    def configure(self, config_json: str, timeout: float) -> None: ...
    def snapshot_json(self) -> str: ...
    def read(self, timeout: float) -> dict[str, Any]: ...

def serial_ports() -> list[str]: ...
def discover_ble_json(timeout: float) -> str: ...
def decode_frames(data: bytes, gains: tuple[int, ...]) -> dict[str, Any]: ...
